# -*- coding: utf-8 -*-
{
    "name": "MedIoT Command Center",
    "version": "19.0.1.0.0",
    "category": "Healthcare",
    "summary": "Doctor dashboard for real-time patient monitoring + alerts + history",
    "author": "Farah Mehrez",
    "depends": [
        "base",
        "web",
        "mail",
        "auth_signup",
        "website",
    ],
    "data": [
        "security/security.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/patient_demo.xml",
        "views/patient_views.xml",
        "views/vital_reading_views.xml",
        "views/alert_views.xml",
        "views/device_views.xml",
        "views/settings_views.xml",
        "views/auth_pages.xml",
        "views/role_select_template.xml",
        "views/login_template.xml",
        "views/signup_template.xml",
        "views/menus.xml",
        "reports/patient_medical_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "med_iot_command_center/static/src/js/personal_greeting.js",
            "med_iot_command_center/static/src/js/dashboard.js",
            "med_iot_command_center/static/src/xml/dashboard.xml",
            "med_iot_command_center/static/src/scss/dashboard.scss",
            "med_iot_command_center/static/src/css/dashboard.css",
            "med_iot_command_center/static/src/css/patient.css",
        ],
        "web.assets_frontend": [
            "med_iot_command_center/static/src/js/auth_portal.js",
            "med_iot_command_center/static/src/css/auth_portal.css",
            "med_iot_command_center/static/src/js/landing_counters.js",
        ],
    },
    "application": True,
    "images": ["static/description/icon.png"],
    "license": "LGPL-3",
}
